#!/bin/bash

set -xe

PROJECT=ExampleBankingApp.xcodeproj
SCHEME=ExampleBankingApp
TARGET=ExampleBankingApp
CONFIGURATION=Release
SDK=iphoneos

git checkout ExampleBankingApp

rm -rf headers headers.obf build build.obf

if ! which ios-class-guard; then
	brew install ios-class-guard
fi

# Build project to fetch symbols
xctool \
	-project "$PROJECT" \
	-scheme "$SCHEME" \
	-configuration "$CONFIGURATION" \
	-sdk "$SDK" \
	clean build \
	OBJROOT=build/ \
	SYMROOT=build/

SYMBOLS_FILE="$PWD/symbols.h"

find . -name '*-Prefix.pch' -exec sed -i .bak '1i\
'"#import \"$SYMBOLS_FILE\"
" "{}" \;

class-dump -H -o headers build/$CONFIGURATION-$SDK/$TARGET.app/$TARGET

# Obfuscate project
ios-class-guard \
	--sdk-root /Applications/Xcode-5.1.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk \
	-O symbols.h \
	build/$CONFIGURATION-$SDK/$TARGET.app/$TARGET

# Build project to fetch symbols
xctool \
	-project "$PROJECT" \
	-scheme "$SCHEME" \
	-configuration "$CONFIGURATION" \
	-sdk "$SDK" \
	clean build \
	OBJROOT=build.obf/ \
	SYMROOT=build.obf/

class-dump -H -o headers.obf build.obf/$CONFIGURATION-$SDK/$TARGET.app/$TARGET
