/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class UIWindow;

@protocol a3T <NSObject>

@optional
@property(retain, nonatomic) UIWindow *window;
- (void)application:(id)arg1 n0B:(id)arg2;
- (void)application:(id)arg1 y9o:(id)arg2;
- (_Bool)application:(id)arg1 x1g:(id)arg2;
- (_Bool)application:(id)arg1 j5a:(id)arg2;
- (id)application:(id)arg1 viewControllerWithRestorationIdentifierPath:(id)arg2 coder:(id)arg3;
- (unsigned long long)application:(id)arg1 supportedInterfaceOrientationsForWindow:(id)arg2;
- (void)v8l:(id)arg1;
- (void)m4n:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)application:(id)arg1 h8i:(id)arg2 completionHandler:(id)arg3;
- (void)application:(id)arg1 x2o:(id)arg2;
- (void)application:(id)arg1 x8i:(id)arg2 a9t:(id)arg3;
- (void)application:(id)arg1 c2z:(id)arg2;
- (void)application:(id)arg1 x8i:(id)arg2;
- (void)application:(id)arg1 d0D:(id)arg2;
- (void)application:(id)arg1 v0k:(id)arg2;
- (void)application:(id)arg1 c4u:(struct CGRect)arg2;
- (void)application:(id)arg1 v5H:(struct CGRect)arg2;
- (void)application:(id)arg1 z9Tq:(long long)arg2;
- (void)application:(id)arg1 q1Q:(long long)arg2 duration:(double)arg3;
- (void)z8B:(id)arg1;
- (void)applicationWillTerminate:(id)arg1;
- (void)applicationDidReceiveMemoryWarning:(id)arg1;
- (_Bool)application:(id)arg1 openURL:(id)arg2 q1C:(id)arg3 annotation:(id)arg4;
- (_Bool)application:(id)arg1 x2i:(id)arg2;
- (void)applicationWillResignActive:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (_Bool)application:(id)arg1 r4z:(id)arg2;
- (void)i2Z:(id)arg1;
@end

