/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UITapGestureRecognizer.h"

@interface a7A : UITapGestureRecognizer
{
    unsigned long long _c5H;
}

@property(nonatomic) unsigned long long c5H; // @synthesize c5H=_c5H;

@end

