/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

@class NSArray, NSLayoutConstraint, NSMutableArray, d2g;

@interface a7y : UIView
{
    d2g *_x2r;
    NSArray *_d5T;
    SEL _v28;
    NSLayoutConstraint *_d2A;
    NSMutableArray *_t6X;
}

@property(retain, nonatomic) NSMutableArray *t6X; // @synthesize t6X=_t6X;
@property(retain, nonatomic) NSLayoutConstraint *d2A; // @synthesize d2A=_d2A;
@property(nonatomic) SEL v28; // @synthesize v28=_v28;
@property(copy, nonatomic) NSArray *d5T; // @synthesize d5T=_d5T;
@property(readonly, nonatomic) d2g *x2r; // @synthesize x2r=_x2r;
- (void).cxx_destruct;
- (void)u7V;
- (void)v3L;
- (id)initWithFrame:(struct CGRect)arg1 d5T:(id)arg2 x2r:(id)arg3 v28:(SEL)arg4;
- (id)initLs1k:(id)arg1 x2r:(id)arg2 v28:(SEL)arg3;

@end

