/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UITableViewCell.h"

#import "UIGestureRecognizerDelegate.h"
#import "UIScrollViewDelegate.h"

@class NSArray, NSLayoutConstraint, UILongPressGestureRecognizer, UIScrollView, UITableView, UITapGestureRecognizer, UIView, a7y;

@interface d2g : UITableViewCell <UIScrollViewDelegate, UIGestureRecognizerDelegate>
{
    NSArray *_t8c;
    NSArray *_p5x;
    id <k25> _delegate;
    UITableView *_containingTableView;
    long long _y9F;
    double _u8G;
    UIScrollView *_r6k;
    a7y *_i7I;
    a7y *_a63;
    UIView *_e9t;
    UIView *_q9m;
    NSLayoutConstraint *_f3A;
    NSLayoutConstraint *_b7e;
    UILongPressGestureRecognizer *_j0P;
    UITapGestureRecognizer *_a3Q;
}

@property(retain, nonatomic) UITapGestureRecognizer *a3Q; // @synthesize a3Q=_a3Q;
@property(retain, nonatomic) UILongPressGestureRecognizer *j0P; // @synthesize j0P=_j0P;
@property(retain, nonatomic) NSLayoutConstraint *b7e; // @synthesize b7e=_b7e;
@property(retain, nonatomic) NSLayoutConstraint *f3A; // @synthesize f3A=_f3A;
@property(retain, nonatomic) UIView *q9m; // @synthesize q9m=_q9m;
@property(retain, nonatomic) UIView *e9t; // @synthesize e9t=_e9t;
@property(retain, nonatomic) a7y *a63; // @synthesize a63=_a63;
@property(retain, nonatomic) a7y *i7I; // @synthesize i7I=_i7I;
@property(retain, nonatomic) UIScrollView *r6k; // @synthesize r6k=_r6k;
@property(nonatomic) double u8G; // @synthesize u8G=_u8G;
@property(nonatomic) long long y9F; // @synthesize y9F=_y9F;
@property(nonatomic) __weak UITableView *containingTableView; // @synthesize containingTableView=_containingTableView;
@property(nonatomic) __weak id <k25> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSArray *p5x; // @synthesize p5x=_p5x;
@property(copy, nonatomic) NSArray *t8c; // @synthesize t8c=_t8c;
- (void).cxx_destruct;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)s3k;
- (struct CGPoint)b51:(long long)arg1;
- (double)c4l;
- (double)t9T;
- (double)n6a;
- (void)r1Z:(_Bool)arg1;
- (void)r11:(id)arg1;
- (void)s7q:(id)arg1;
- (void)j9A;
- (void)p22;
- (void)a0X:(id)arg1;
- (void)g0o:(id)arg1;
- (_Bool)u4r;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)prepareForReuse;
- (void)layoutSubviews;
- (void)didMoveToSuperview;
- (void)m4b;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 containingTableView:(id)arg3 t8c:(id)arg4 p5x:(id)arg5;

@end

