/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSMutableArray.h"

@interface NSMutableArray (x7t)
- (void)z6i:(id)arg1 w8e:(id)arg2 q2P:(id)arg3;
- (void)z6i:(id)arg1 u0Z:(id)arg2;
- (void)z6i:(id)arg1 title:(id)arg2;
@end

