/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "k25.h"

@class NSArray, NSMutableArray, UIRefreshControl, UITableView;

@interface ViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, k25>
{
    NSArray *_sections;
    NSMutableArray *_testArray;
    _Bool _useCustomCells;
    UITableView *_tableView;
    UIRefreshControl *_refreshControl;
}

@property(nonatomic) __weak UIRefreshControl *refreshControl; // @synthesize refreshControl=_refreshControl;
@property(nonatomic) _Bool useCustomCells; // @synthesize useCustomCells=_useCustomCells;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (_Bool)swipeableTableViewCellShouldHideUtilityButtonsOnSwipe:(id)arg1;
- (void)swipeableTableViewCell:(id)arg1 didTriggerRightUtilityButtonWithIndex:(long long)arg2;
- (void)swipeableTableViewCell:(id)arg1 didTriggerLeftUtilityButtonWithIndex:(long long)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)leftButtons;
- (id)rightButtons;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)toggleCells:(id)arg1;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewDidLoad;

@end

