/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSMutableArray.h"

@interface NSMutableArray (SWUtilityButtons)
- (void)sw_addUtilityButtonWithColor:(id)arg1 normalIcon:(id)arg2 selectedIcon:(id)arg3;
- (void)sw_addUtilityButtonWithColor:(id)arg1 icon:(id)arg2;
- (void)sw_addUtilityButtonWithColor:(id)arg1 title:(id)arg2;
@end

