/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UITableViewCell.h"

#import "UIGestureRecognizerDelegate.h"
#import "UIScrollViewDelegate.h"

@class NSArray, NSLayoutConstraint, SWUtilityButtonView, UILongPressGestureRecognizer, UIScrollView, UITableView, UITapGestureRecognizer, UIView;

@interface SWTableViewCell : UITableViewCell <UIScrollViewDelegate, UIGestureRecognizerDelegate>
{
    NSArray *_leftUtilityButtons;
    NSArray *_rightUtilityButtons;
    id <SWTableViewCellDelegate> _delegate;
    UITableView *_containingTableView;
    long long _cellState;
    double _additionalRightPadding;
    UIScrollView *_cellScrollView;
    SWUtilityButtonView *_leftUtilityButtonsView;
    SWUtilityButtonView *_rightUtilityButtonsView;
    UIView *_leftUtilityClipView;
    UIView *_rightUtilityClipView;
    NSLayoutConstraint *_leftUtilityClipConstraint;
    NSLayoutConstraint *_rightUtilityClipConstraint;
    UILongPressGestureRecognizer *_longPressGestureRecognizer;
    UITapGestureRecognizer *_tapGestureRecognizer;
}

@property(retain, nonatomic) UITapGestureRecognizer *tapGestureRecognizer; // @synthesize tapGestureRecognizer=_tapGestureRecognizer;
@property(retain, nonatomic) UILongPressGestureRecognizer *longPressGestureRecognizer; // @synthesize longPressGestureRecognizer=_longPressGestureRecognizer;
@property(retain, nonatomic) NSLayoutConstraint *rightUtilityClipConstraint; // @synthesize rightUtilityClipConstraint=_rightUtilityClipConstraint;
@property(retain, nonatomic) NSLayoutConstraint *leftUtilityClipConstraint; // @synthesize leftUtilityClipConstraint=_leftUtilityClipConstraint;
@property(retain, nonatomic) UIView *rightUtilityClipView; // @synthesize rightUtilityClipView=_rightUtilityClipView;
@property(retain, nonatomic) UIView *leftUtilityClipView; // @synthesize leftUtilityClipView=_leftUtilityClipView;
@property(retain, nonatomic) SWUtilityButtonView *rightUtilityButtonsView; // @synthesize rightUtilityButtonsView=_rightUtilityButtonsView;
@property(retain, nonatomic) SWUtilityButtonView *leftUtilityButtonsView; // @synthesize leftUtilityButtonsView=_leftUtilityButtonsView;
@property(retain, nonatomic) UIScrollView *cellScrollView; // @synthesize cellScrollView=_cellScrollView;
@property(nonatomic) double additionalRightPadding; // @synthesize additionalRightPadding=_additionalRightPadding;
@property(nonatomic) long long cellState; // @synthesize cellState=_cellState;
@property(nonatomic) __weak UITableView *containingTableView; // @synthesize containingTableView=_containingTableView;
@property(nonatomic) __weak id <SWTableViewCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSArray *rightUtilityButtons; // @synthesize rightUtilityButtons=_rightUtilityButtons;
@property(copy, nonatomic) NSArray *leftUtilityButtons; // @synthesize leftUtilityButtons=_leftUtilityButtons;
- (void).cxx_destruct;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)updateCellState;
- (struct CGPoint)contentOffsetForCellState:(long long)arg1;
- (double)utilityButtonsPadding;
- (double)rightUtilityButtonsWidth;
- (double)leftUtilityButtonsWidth;
- (void)hideUtilityButtonsAnimated:(_Bool)arg1;
- (void)leftUtilityButtonHandler:(id)arg1;
- (void)rightUtilityButtonHandler:(id)arg1;
- (void)deselectCell;
- (void)selectCell;
- (void)scrollViewTapped:(id)arg1;
- (void)scrollViewPressed:(id)arg1;
- (_Bool)shouldHighlight;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)prepareForReuse;
- (void)layoutSubviews;
- (void)didMoveToSuperview;
- (void)initializer;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 containingTableView:(id)arg3 leftUtilityButtons:(id)arg4 rightUtilityButtons:(id)arg5;

@end

