/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol SWTableViewCellDelegate <NSObject>

@optional
- (_Bool)swipeableTableViewCell:(id)arg1 canSwipeToState:(long long)arg2;
- (_Bool)swipeableTableViewCellShouldHideUtilityButtonsOnSwipe:(id)arg1;
- (void)swipeableTableViewCell:(id)arg1 scrollingToState:(long long)arg2;
- (void)swipeableTableViewCell:(id)arg1 didTriggerRightUtilityButtonWithIndex:(long long)arg2;
- (void)swipeableTableViewCell:(id)arg1 didTriggerLeftUtilityButtonWithIndex:(long long)arg2;
@end

