/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

@class NSArray, NSLayoutConstraint, NSMutableArray, SWTableViewCell;

@interface SWUtilityButtonView : UIView
{
    SWTableViewCell *_parentCell;
    NSArray *_utilityButtons;
    SEL _utilityButtonSelector;
    NSLayoutConstraint *_widthConstraint;
    NSMutableArray *_buttonBackgroundColors;
}

@property(retain, nonatomic) NSMutableArray *buttonBackgroundColors; // @synthesize buttonBackgroundColors=_buttonBackgroundColors;
@property(retain, nonatomic) NSLayoutConstraint *widthConstraint; // @synthesize widthConstraint=_widthConstraint;
@property(nonatomic) SEL utilityButtonSelector; // @synthesize utilityButtonSelector=_utilityButtonSelector;
@property(copy, nonatomic) NSArray *utilityButtons; // @synthesize utilityButtons=_utilityButtons;
@property(readonly, nonatomic) SWTableViewCell *parentCell; // @synthesize parentCell=_parentCell;
- (void).cxx_destruct;
- (void)popBackgroundColors;
- (void)pushBackgroundColors;
- (id)initWithFrame:(struct CGRect)arg1 utilityButtons:(id)arg2 parentCell:(id)arg3 utilityButtonSelector:(SEL)arg4;
- (id)initWithUtilityButtons:(id)arg1 parentCell:(id)arg2 utilityButtonSelector:(SEL)arg3;

@end

