/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UITapGestureRecognizer.h"

@interface SWUtilityButtonTapGestureRecognizer : UITapGestureRecognizer
{
    unsigned long long _buttonIndex;
}

@property(nonatomic) unsigned long long buttonIndex; // @synthesize buttonIndex=_buttonIndex;

@end

