/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SWTableViewCell.h"

@class UIImageView, UILabel;

@interface UMTableViewCell : SWTableViewCell
{
    UIImageView *_image;
    UILabel *_label;
}

@property(nonatomic) __weak UILabel *label; // @synthesize label=_label;
@property(nonatomic) __weak UIImageView *image; // @synthesize image=_image;
- (void).cxx_destruct;

@end

